// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: checkChirpOwnership.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const checkChirpOwnerShip = `-- name: CheckChirpOwnerShip :one
SELECT EXISTS(
SELECT id
FROM chirps
WHERE id = $1
AND user_id = $2)
`

type CheckChirpOwnerShipParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckChirpOwnerShip(ctx context.Context, arg CheckChirpOwnerShipParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkChirpOwnerShip, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
