// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: getChirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getChirp = `-- name: GetChirp :one
SELECT id, created_at, updated_at, body, user_id
FROM chirps
WHERE user_id = $1
`

func (q *Queries) GetChirp(ctx context.Context, userID uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getChirp, userID)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
